spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attus_desafio_backend
    username: root
    password: 3285
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update