CREATE TABLE tbl_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    city VARCHAR(255),
    default_address BOOLEAN,
    house_number INTEGER,
    province VARCHAR(255),
    street_address VARCHAR(255),
    zip_code VARCHAR(255),
    person_id BIGINT,
    PRIMARY KEY (id)
);
